python/bifrost/DataType.py, python/bifrost/block.py, src/Makefile, src/guantize.cu, src/guantize.hu, src/gunpack.cu, src/gunpack.hu, src/quantize.cpp, src/unpack.cpp, src/utils.hu, test/test_guantize.py, test/test_gunpack.py, test/test_resizing.py
Add support for GPU-based unpacking and quantization (fourth attempt). This includes:
* GPU functions for unpacking integer data into 'i8'/'ci8'
* Functions to unpack integer data and promote to float/double
* Support for unpacking 1-bit data as:
* 0 unpacks to -1
* 1 unpacks to 1
* Preliminary support for packing into 'i2'/'ci2' and 'i1'/'ci1'. Full support held up by a check for padded arrays.
=> GPU Unpack, take four

src/proclog.cpp, tools/like_bmon.py
A couple of fixes for the ProcLog module.  The first is to wrap the `/dev/shm/bifrost/` directory cleanup in a try...catch block to deal with files owned by other users and their pipelines.  The second is a change to the ProcLog name de-duplicator to make it work with the `module/file` structure that is currently used so that duplicate modules use separate directories.
=> Multi-logging fixes

.travis.yml, Dockerfile.cpu, Dockerfile.gpu, Dockerfile_prereq.gpu, test/download_test_data.sh
This is a minor update to the Dockerfiles to get around the deprecation of Python2.7 in the pip version from https://bootstrap.pypa.io/get-pip.py  The Dockerfiles now use the Python2.7-friendly version of pip that ships with Ubuntu.
=> Minor Docker Update

.gitignore, python/Makefile.in, python/bifrost/__init__.py, python/bifrost/version/__main__.py, python/setup.py
Just enables a simple command to print out version and copyright info:
```
% python -m bifrost.version
bifrost 0.9.0.dev+g2bc27cc
Copyright (c) 2016-2020, The Bifrost Authors. All rights reserved.
Copyright (c) 2016, NVIDIA CORPORATION. All rights reserved.
License: BSD 3-Clause
```
I think it would be nice to offer many of the 'tool' scripts with this interface, e.g. `python -m bifrost.telemetry --enable` rather than (or I guess in addition to) a script file in `bin/`.
=> Support `python -m bifrost.version` command

CHANGELOG, Makefile.in, python/Makefile.in, src/Makefile.in, src/autodep.mk
Drop the `DRY_RUN` distinction in makefiles (`make -n` works better) and quit trying to use carriage returns `\r` in makefile output. Please see commit messages for more rationale!
=> Simplify makefiles

.github/workflows/nix.yml, CHANGELOG, flake.lock, flake.nix
This is a start on specifying a “flake” for building bifrost with Nix. A flake is a format that pins all dependencies to support reproducible builds. This initial version includes github workflow for building with different releases of the nixpkgs tree (containing compilers, python dependencies, etc.) and different versions of python, then running the tests on all those configurations. (This builds on autoconf.) More background: [nixos.org](https://nixos.org/), [Flakes on Nix wiki](https://nixos.wiki/wiki/Flakes), [Flakes tutorial from tweag.io](https://www.tweag.io/blog/2020-05-25-flakes/)
It doesn't yet support GPU builds, though I've gotten it _mostly_ to work. It's a little tricky to integrate because the `libcuda.so.1` must come from the host platform, so it agrees with the kernel …
=> Nix build using flake

src/Socket.hpp, src/udp_socket.cpp
It looks like we're trying to use `enum sock_type` to impose a more
limited type on the `int` specified by `::socket`. But it wasn't all
the way supported, because the constructor took a general
`int` (doesn't seem to be used that way within bifrost) and there were
several comparisons between `SOCK_STREAM` (respectively `SOCK_DGRAM`)
integer constants and enum-enabled `BF_SOCK_STREAM` (`BF_SOCK_DGRAM`).
So this takes that goal further, using the enum version only. An
alternative though (in case some other client code is using a general
integer for other socket types) is just to eliminate `enum sock_type`
and (if necessary) throw an exception if passed a `SOCK_*` constant
other than those we support.
The warnings were...
```
In file included from address.cpp:30:
Socket.hpp: In member …
```
=> In Socket.hpp, prevent warnings about sock_type comparison

configure, configure.ac, test/test_fft.py
“Fixes” is a strong word, but I suppose this can close #180. I'm just updating the warnings and exclusion of the c2r tests for CUDA 11.7, which were reported therein. @jaycedowell, I guess it would need an autoconf rerun before merge.
=> cufft c2r issue still persists with CUDA 11.7

python/bifrost/dtype.py, python/bifrost/ndarray.py, test/test_ndarray.py
This allows a bifrost ndarray to be instantiated from a BFarray struct (as returned by `ndarray.as_BFarray()`)
Minimal example:
```python
a = bifrost.ndarray(np.arange(100), dtype='i32')
aa = a.as_BFarray()
b = bifrost.ndarray(aa)
np.testing.assert_equal(a, b)
```
=> Create ndarray from BFarray ctypes struct 

config/cuda.m4, configure, configure.ac, src/linalg_kernels.cu, src/linalg_kernels.h
This PR enables auto-detection of the GPU shared memory per block.  It also changes `linalg_kernels.cu` to use `BF_GPU_SHAREDMEM` when determining if an array can fit into shared memory.
=> Auto-detect GPU shared memory

.github/workflows/main.yml, python/bifrost/guppi_raw.py, test/test_scripts.py
This PR addresses #208 where linting of the scripts in `tools` and testing of the scripts in `testbench` stopped when we moved away from Jenkins.
.. note:: The linting is only down by Py3 now.
=> Re-enable testing the scripts

ROADMAP.md, config/cuda.m4, config/doxygen.m4, config/openmp.m4, config/stdcxx.m4, config/withprog.m4, configure, flake.nix, src/Complex.hpp, src/Vector.hpp, src/linalg.cu, src/linalg_kernels.cu
This PR drops support for CUDA versions prior to 10.  This is done through a combination of catching old versions of CUDA in `configure` and dropping the `__CUDACC_VER_MAJOR__` tests that toggle for features before/at  9.
=> Only support CUDA 10+

python/bifrost/DataType.py, python/bifrost/block.py, test/test_block.py, test/test_map.py, test/test_resizing.py, test/test_scripts.py
Deprecation warnings should be gone. Notable is the change from np.int8 to np.uint8 in the ci4 datatype. One test failed because I was testing against numpy 1.25 and one of our tutorial files still requires numba, which is incompatible with numpy 1.25
=> Fix dep warning

python/bifrost/sigproc2.py
This PR changes how `bifrost.sigproc2`s internal buffer is resized.  Rather than doing an in-place resize (which could cause knock-on problems for other blocks accessing that data) the buffer is re-allocated when a resize is needed.  This should be the last task for #214.
=> Fixed buffer resizing in `bifrost.sigproc2`

src/linalg.cu, src/linalg_kernels.cu
Updated the linalg algorithms to tune for performance
=> Update linalg algos

src/trace.hpp, src/utils.hpp
My newish laptop has gcc13 by default. It needs explicit `<cstdint>` to define `uint64_t` and friends.
https://gcc.gnu.org/gcc-13/porting_to.html
=> Explicitly include cstdint for gcc13

.github/workflows/main.yml
The transcript says:
```
Version 3.6 was not found in the local cache
Error: The version '3.6' with architecture 'arm64' was not found for macOS 14.4.1.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
That list does contain some 3.6.x, but then I noticed the part about "architecture arm64"… so [this comment](https://github.com/actions/setup-python/issues/856#issuecomment-2083483754) seems to be relevant:
> For me this looks like it's probably that the macos-latest Github action runner appears to have switched to an M1 ARM mac, where at least last week macos-latest was an x86 mac.
So I see a couple of options:
- Pin `macos-latest` to an earlier revision so we're still ensuring x86, or
- Drop 3.6 …
=> Mac builds with Python 3.6 are failing in Github Actions

test/test_scripts.py, test/test_tutorial.py, tools/like_pmap.py
Two places where regexes used `\d` without being "raw" strings. The one in `like_pmap` was showing up in tests as:
```
like_pmap:95: DeprecationWarning: invalid escape sequence '\d'
```
~Though it's not yet clear to me how/why `like_pmap` is being imported into any tests...?~
=> Fix DeprecationWarning: invalid escape sequence \d

src/fileutils.cpp, src/fileutils.hpp
Fixes #232.
I think this is ready to go. There's a self-contained test program at the bottom of the file, it's easy to compile and test in isolation.
Is a `cerr` message good enough?
=> Lockfile will warn periodically if waiting more than 5s

python/bifrost/telemetry/__init__.py
I came across this problem of trying to figure out how old of Python I really need to support with LSL and thought it might be useful for Bifrost as well.
=> Update telemetry to include the Python version

.github/workflows/main.yml, BifrostDemo.ipynb, README.md, configure, configure.ac, docs/.readthedocs.yaml, docs/source/Getting-started-guide.rst, tutorial/00_getting_started.ipynb, tutorial/01_useful_functions.ipynb, tutorial/02_building_complexity.ipynb, tutorial/03_putting_it_together.ipynb, tutorial/04_pipelines.ipynb, tutorial/05_block_logging.ipynb, tutorial/06_data_capture.ipynb, tutorial/07_high_level_api.ipynb
Fixes #246 at some level.
This PR moves over to using universal-ctags.  This seems to be a successor to exuberant-ctags that is available on Ubuntu, home brew, and Redhat-based system.
Things left to do:
=> Switch to universal-ctags
